### PR TITLE
Creating Carb.js w/ getter & setter function

### PR DESCRIPTION
**Pull request by davis-dyer**

### CODE REVIEW

**Review by priteshzaver — APPROVED** [review]
👍

**Review by tiffanyautumn — CHANGES_REQUESTED** [review]
correct setter function

**Review by Alexanderthefun — APPROVED** [review]
perfection

**Review by tiffanyautumn — APPROVED** [review]
As long as you all are okay with the order.js being included

**Review by mhurtado2 — APPROVED** [review]
sickkk

**Review by priteshzaver — APPROVED** [review]
👍

**Pull request merged**
